'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { RetroASCII, PATTERN_NAMES } from '../components/RetroASCII';
import { ColorPicker } from '../components/ColorPicker';
import { CopyCodeButton } from '../components/CopyCodeButton';
import { AboutButton } from '../components/AboutButton';
import { Toast } from '../components/Toast';
import { COLOR_PALETTE, DEFAULT_COLORS } from '../lib/colorPalette';
import styles from './page.module.css';

function syncCSSVars(indices: number[]) {
  const root = document.documentElement.style;
  const colors = indices.map((i) => COLOR_PALETTE[i]);

  const primary = colors[0] ?? COLOR_PALETTE[DEFAULT_COLORS[0]];
  const secondary = colors[1] ?? colors[0] ?? COLOR_PALETTE[DEFAULT_COLORS[1]];
  const accent = colors[2] ?? colors[1] ?? colors[0] ?? COLOR_PALETTE[DEFAULT_COLORS[2]];

  root.setProperty('--color-primary', `${primary.rgb.r}, ${primary.rgb.g}, ${primary.rgb.b}`);
  root.setProperty('--color-secondary', `${secondary.rgb.r}, ${secondary.rgb.g}, ${secondary.rgb.b}`);
  root.setProperty('--color-accent', `${accent.rgb.r}, ${accent.rgb.g}, ${accent.rgb.b}`);

  root.setProperty('--color-primary-hex', primary.hex);
  root.setProperty('--color-secondary-hex', secondary.hex);
  root.setProperty('--color-accent-hex', accent.hex);
}

function gridToString(grid: string[][]): string {
  return grid.map((row) => row.join('')).join('\n');
}

export default function Home() {
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 });
  const [selectedColorIndices, setSelectedColorIndices] = useState<number[]>(
    Array.from(DEFAULT_COLORS)
  );
  const [toastVisible, setToastVisible] = useState(false);

  const gridRef = useRef<string[][] | null>(null);
  const patternIndexRef = useRef<number>(0);

  useEffect(() => {
    const updateDimensions = () => {
      setDimensions({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };

    updateDimensions();
    window.addEventListener('resize', updateDimensions);
    return () => window.removeEventListener('resize', updateDimensions);
  }, []);

  useEffect(() => {
    syncCSSVars(selectedColorIndices);
  }, [selectedColorIndices]);

  const activeColors = selectedColorIndices.map((i) => COLOR_PALETTE[i]);

  const handleColorsChange = useCallback((indices: number[]) => {
    setSelectedColorIndices(indices);
  }, []);

  const handleCopy = useCallback(() => {
    const grid = gridRef.current;
    if (!grid) return;

    const patternName = PATTERN_NAMES[patternIndexRef.current] ?? 'Unknown';
    const colorNames = selectedColorIndices.map((i) => COLOR_PALETTE[i].name);
    const colorHexes = selectedColorIndices.map((i) => COLOR_PALETTE[i].hex);
    const asciiArt = gridToString(grid);

    const output = [
      `ASCII Animation Snapshot`,
      `Pattern: ${patternName}`,
      `Colors: ${colorNames.map((n, i) => `${n} (${colorHexes[i]})`).join(', ')}`,
      ``,
      `\`\`\``,
      asciiArt,
      `\`\`\``,
      ``,
      `Generated by ASCII | PostScarcity AI`,
      `https://github.com/postscarcityai/ascii`,
    ].join('\n');

    navigator.clipboard.writeText(output);
    setToastVisible(true);
  }, [selectedColorIndices]);

  return (
    <main className={styles.main}>
      {dimensions.width > 0 && dimensions.height > 0 && (
        <RetroASCII
          width={dimensions.width}
          height={dimensions.height}
          colors={activeColors}
          gridRef={gridRef}
          patternIndexRef={patternIndexRef}
        />
      )}
      <AboutButton />
      <CopyCodeButton onCopy={handleCopy} />
      <ColorPicker
        selectedIndices={selectedColorIndices}
        onColorsChange={handleColorsChange}
      />
      <Toast
        message="Copied to clipboard!"
        detail="Paste this into your AI agent of choice to recreate or riff on this ASCII animation."
        visible={toastVisible}
        onDismiss={() => setToastVisible(false)}
      />
    </main>
  );
}
